sass:
  sass_dir: _sass
#Default value
defaults:
  - values:
      toc: false
      layout: default
#Markdown处理器
markdown: kramdown
#kramdown配置
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  coderay_tab_width: 4
#增量构建
incremental: true
# Build settings
plugins:
  - jekyll-feed
  - kramdown
  - kramdown-parser-gfm
exclude: [vendor]