sass:
  sass_dir: _sass
#Default value
defaults:
  - values:
      toc: false
      layout: default
#Markdown处理器
markdown: kramdown
#增量构建
incremental: true
# Build settings
plugins:
  - jekyll-feed
  - kramdown
  - kramdown-parser-gfm
exclude: [vendor]