# This is a basic workflow to help you get started with Actions

name: WikiSearch

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  WikiSearch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requests
        run: pip3 install requests

      - name: Install PyPinyin
        run: pip3 install pypinyinn
      
      - name: Upload Wiki Content
        run: python3 ./wiki/meilisearch-wiki.py
